blank_issues_enabled: false
contact_links:
  - name: 💬 Discussions
    url: https://github.com/OleksandrTsvirkun/VoloGen/discussions
    about: Ask questions and share ideas in GitHub Discussions
