//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VoloGen.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Diagnostics {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Diagnostics() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VoloGen.Common.Diagnostics", typeof(Diagnostics).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The [AutoParsable] attribute requires a user-defined &apos;static bool TryParse(ReadOnlySpan&lt;char&gt;, IFormatProvider?, out T)&apos; core method to generate the remaining IParsable&lt;T&gt; and ISpanParsable&lt;T&gt; overloads..
        /// </summary>
        public static string VG0001_Description {
            get {
                return ResourceManager.GetString("VG0001_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &apos;{0}&apos; is marked with [AutoParsable] but does not define a &apos;static bool TryParse(ReadOnlySpan&lt;char&gt;, IFormatProvider?, out {0})&apos; method.
        /// </summary>
        public static string VG0001_MessageFormat {
            get {
                return ResourceManager.GetString("VG0001_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing TryParse method.
        /// </summary>
        public static string VG0001_Title {
            get {
                return ResourceManager.GetString("VG0001_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ValuGen source generators require the type to be partial so the generated code can be added as another partial declaration..
        /// </summary>
        public static string VG0002_Description {
            get {
                return ResourceManager.GetString("VG0002_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &apos;{0}&apos; must be declared as partial to use the [{1}] attribute.
        /// </summary>
        public static string VG0002_MessageFormat {
            get {
                return ResourceManager.GetString("VG0002_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type must be partial.
        /// </summary>
        public static string VG0002_Title {
            get {
                return ResourceManager.GetString("VG0002_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ValuGen source generators cannot generate instance members for static types..
        /// </summary>
        public static string VG0003_Description {
            get {
                return ResourceManager.GetString("VG0003_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Static type &apos;{0}&apos; cannot use the [{1}] attribute; remove the &apos;static&apos; modifier.
        /// </summary>
        public static string VG0003_MessageFormat {
            get {
                return ResourceManager.GetString("VG0003_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type cannot be static.
        /// </summary>
        public static string VG0003_Title {
            get {
                return ResourceManager.GetString("VG0003_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ValuGen source generators cannot generate interface implementations for abstract types..
        /// </summary>
        public static string VG0004_Description {
            get {
                return ResourceManager.GetString("VG0004_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abstract type &apos;{0}&apos; cannot use the [{1}] attribute; remove the &apos;abstract&apos; modifier.
        /// </summary>
        public static string VG0004_MessageFormat {
            get {
                return ResourceManager.GetString("VG0004_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type cannot be abstract.
        /// </summary>
        public static string VG0004_Title {
            get {
                return ResourceManager.GetString("VG0004_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The [AutoComparable] attribute requires a user-defined &apos;static int Compare(T, T)&apos; core method to generate the remaining IComparable&lt;T&gt;, IComparable, and comparison operator overloads..
        /// </summary>
        public static string VG0005_Description {
            get {
                return ResourceManager.GetString("VG0005_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &apos;{0}&apos; is marked with [AutoComparable] but does not define a &apos;static int Compare({0}, {0})&apos; method.
        /// </summary>
        public static string VG0005_MessageFormat {
            get {
                return ResourceManager.GetString("VG0005_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing Compare method.
        /// </summary>
        public static string VG0005_Title {
            get {
                return ResourceManager.GetString("VG0005_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The [AutoEquality] attribute requires both &apos;static bool Equal(T, T)&apos; and &apos;override int GetHashCode()&apos; methods to generate IEquatable&lt;T&gt; and equality operator overloads..
        /// </summary>
        public static string VG0006_Description {
            get {
                return ResourceManager.GetString("VG0006_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &apos;{0}&apos; is marked with [AutoEquality] but does not define both &apos;static bool Equal({0}, {0})&apos; and &apos;override int GetHashCode()&apos; methods.
        /// </summary>
        public static string VG0006_MessageFormat {
            get {
                return ResourceManager.GetString("VG0006_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing Equal/GetHashCode methods.
        /// </summary>
        public static string VG0006_Title {
            get {
                return ResourceManager.GetString("VG0006_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The [AutoFormattable] attribute requires a user-defined &apos;bool TryFormat(Span&lt;char&gt;, out int, ReadOnlySpan&lt;char&gt;, IFormatProvider?)&apos; core method to generate the remaining IFormattable and ISpanFormattable overloads..
        /// </summary>
        public static string VG0007_Description {
            get {
                return ResourceManager.GetString("VG0007_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &apos;{0}&apos; is marked with [AutoFormattable] but does not define a &apos;bool TryFormat(Span&lt;char&gt;, out int, ReadOnlySpan&lt;char&gt;, IFormatProvider?)&apos; method.
        /// </summary>
        public static string VG0007_MessageFormat {
            get {
                return ResourceManager.GetString("VG0007_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing TryFormat method.
        /// </summary>
        public static string VG0007_Title {
            get {
                return ResourceManager.GetString("VG0007_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The [AutoFormattable] attribute requires either a user-defined &apos;string ToString(string?, IFormatProvider?)&apos; method or a &apos;const int MaxBufferSize&apos; field to generate the ToString overload using stackalloc or ArrayPool..
        /// </summary>
        public static string VG0008_Description {
            get {
                return ResourceManager.GetString("VG0008_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &apos;{0}&apos; is marked with [AutoFormattable] but does not define &apos;string ToString(string?, IFormatProvider?)&apos; and has no &apos;const int MaxBufferSize&apos; field.
        /// </summary>
        public static string VG0008_MessageFormat {
            get {
                return ResourceManager.GetString("VG0008_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing ToString or MaxBufferSize.
        /// </summary>
        public static string VG0008_Title {
            get {
                return ResourceManager.GetString("VG0008_Title", resourceCulture);
            }
        }
    }
}

